import type { AccountType } from "./contracts";

type Definition = [
  code: string,
  name: string,
  type: AccountType,
  purpose?: string,
  cashKind?: "bank" | "cash" | "card",
  normalSide?: "debit" | "credit",
];
const definitions: Definition[] = [
  ["1000", "Checking", "asset", "checking", "bank"],
  ["1010", "Savings", "asset", "savings", "bank"],
  ["1100", "Undeposited funds", "asset", "undeposited_funds", "cash"],
  ["1200", "Transfers in transit", "asset", "transfers_in_transit"],
  ["1500", "Equipment", "asset", "equipment"],
  [
    "1590",
    "Accumulated depreciation",
    "asset",
    "accumulated_depreciation",
    undefined,
    "credit",
  ],
  ["1600", "Due from shareholder", "asset", "due_from_shareholder"],
  ["2000", "Business card", "liability", "business_card", "card"],
  ["2100", "Net salary payable", "liability", "net_salary_payable"],
  ["2110", "Payroll taxes payable", "liability", "payroll_taxes_payable"],
  ["2120", "Other payroll deductions", "liability", "payroll_deductions"],
  [
    "2130",
    "Retirement contributions payable",
    "liability",
    "retirement_payable",
  ],
  [
    "2200",
    "Customer funds pending classification",
    "liability",
    "customer_funds",
  ],
  ["2500", "Loans payable", "liability", "loans_payable"],
  ["2600", "Loan from shareholder", "liability", "shareholder_loan"],
  ["2700", "Due to shareholder", "liability", "due_to_shareholder"],
  ["3000", "Shareholder capital", "equity", "shareholder_capital"],
  ["3100", "Shareholder contributions", "equity", "contributions"],
  [
    "3200",
    "Shareholder distributions",
    "equity",
    "distributions",
    undefined,
    "debit",
  ],
  ["3900", "Opening balance equity", "equity", "opening_balance_equity"],
  ["3910", "Opening retained earnings", "equity", "opening_retained_earnings"],
  ["4000", "Consulting revenue", "income", "consulting"],
  ["4100", "Retainer revenue", "income", "retainers"],
  ["4200", "Product and SaaS revenue", "income", "products"],
  ["4300", "Affiliate and referral revenue", "income", "affiliate"],
  ["4400", "Customer reimbursements", "income", "reimbursements"],
  ["4800", "Other income", "income", "other_income"],
  ["4900", "Uncategorized income", "income", "uncategorized_income"],
  ["5000", "Contractors", "expense", "contractors"],
  ["5100", "Software", "expense", "software"],
  ["5110", "Hosting", "expense", "hosting"],
  ["5120", "AI and API services", "expense", "ai_api"],
  ["5200", "Marketing", "expense", "marketing"],
  ["5300", "Professional services", "expense", "professional_services"],
  ["5400", "Merchant fees", "expense", "merchant_fees"],
  ["5410", "Bank fees", "expense", "bank_fees"],
  ["5500", "Office supplies", "expense", "office_supplies"],
  ["5600", "Travel", "expense", "travel"],
  ["5610", "Meals", "expense", "meals"],
  ["5700", "Insurance", "expense", "insurance"],
  ["6000", "Officer compensation", "expense", "officer_compensation"],
  ["6100", "Other wages", "expense", "other_wages"],
  ["6200", "Employer payroll taxes", "expense", "employer_payroll_taxes"],
  ["6210", "Payroll fees", "expense", "payroll_fees"],
  [
    "6300",
    "Shareholder health insurance",
    "expense",
    "shareholder_health_insurance",
  ],
  [
    "6400",
    "Employer retirement contributions",
    "expense",
    "employer_retirement",
  ],
  ["6500", "Taxes and licenses", "expense", "taxes_licenses"],
  ["6600", "Education", "expense", "education"],
  ["6700", "Depreciation", "expense", "depreciation"],
  ["6800", "Interest", "expense", "interest"],
  ["6810", "Documented currency differences", "expense", "fx_differences"],
  ["6900", "Other expenses", "expense", "other_expenses"],
  ["6990", "Uncategorized expense", "expense", "uncategorized_expense"],
];
/** These stable IDs belong only to the optional new-books chart. Wave mappings preserve source identity. */
export const defaultChart = definitions.map(
  ([code, name, account_type, purpose, cash_kind, normal_side], i) => ({
    id: `accc0000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
    code,
    name,
    account_type,
    purpose,
    cash_kind: cash_kind ?? ("none" as const),
    normal_side:
      normal_side ??
      (account_type === "asset" || account_type === "expense"
        ? "debit"
        : "credit"),
  }),
);
