import { readFile, writeFile } from "node:fs/promises";
import { accountingTestDb } from "./accounting-test-db";

// Read only a fresh in-memory fixture catalog. Never connect to an external database.
async function main() {
  const db = await accountingTestDb();
  const quote = (s: string) => '"' + s.replaceAll('"', '""') + '"';
  const literal = (s: string) => "'" + s.replaceAll("'", "''") + "'";
  const predicate =
    "(c.relnamespace='accounting'::regnamespace OR (c.relnamespace='public'::regnamespace AND c.relname='business_profile'))";
  try {
    await db.exec("RESET ROLE; SET search_path = public, pg_catalog");
    const tables = (
      await db.query<{
        oid: number;
        name: string;
        relname: string;
        relrowsecurity: boolean;
        relforcerowsecurity: boolean;
        acl: boolean;
      }>(
        `SELECT c.oid,n.nspname||'.'||c.relname name,c.relname,c.relrowsecurity,c.relforcerowsecurity,c.relacl IS NOT NULL acl FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE ${predicate} AND c.relkind='r' ORDER BY name`,
      )
    ).rows;
    const constraints = (
      await db.query<{
        conrelid: number;
        confrelid: number;
        conname: string;
        contype: string;
        definition: string;
      }>(
        `SELECT k.conrelid,k.confrelid,k.conname,k.contype,pg_get_constraintdef(k.oid) definition FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid WHERE ${predicate} ORDER BY k.conname`,
      )
    ).rows;
    const sql = [
      "-- ACCOUNTING CATALOG BEGIN",
      "-- Generated by scripts/regenerate-accounting-schema.ts from the applied fresh catalog.",
      "CREATE SCHEMA accounting;",
      "REVOKE ALL ON SCHEMA accounting FROM PUBLIC, anon, authenticated, service_role;",
      "GRANT USAGE ON SCHEMA accounting TO authenticated, service_role;",
      "SET check_function_bodies = false;",
    ];
    const emitted = new Set<number>();
    while (emitted.size < tables.length) {
      const table = tables.find(
        (t) =>
          !emitted.has(t.oid) &&
          constraints
            .filter(
              (c) =>
                c.conrelid === t.oid &&
                c.contype === "f" &&
                c.confrelid !== t.oid,
            )
            .every(
              (c) =>
                !tables.some((t) => t.oid === c.confrelid) ||
                emitted.has(c.confrelid),
            ),
      );
      if (!table)
        throw new Error(
          "Foreign key cycle requires an explicit snapshot decision.",
        );
      const columns = (
        await db.query<{
          attname: string;
          type: string;
          attnotnull: boolean;
          attidentity: string;
          default_value: string | null;
        }>(
          "SELECT a.attname,format_type(a.atttypid,a.atttypmod) type,a.attnotnull,a.attidentity,pg_get_expr(d.adbin,d.adrelid) default_value FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=$1 AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum",
          [table.oid],
        )
      ).rows;
      sql.push(
        `CREATE TABLE ${table.name} (\n` +
          [
            ...columns.map(
              (c) =>
                `  ${quote(c.attname)} ${c.type}${c.attidentity ? ` GENERATED ${c.attidentity === "a" ? "ALWAYS" : "BY DEFAULT"} AS IDENTITY` : c.default_value !== null ? ` DEFAULT ${c.default_value}` : ""}${c.attnotnull ? " NOT NULL" : ""}`,
            ),
            ...constraints
              .filter((c) => c.conrelid === table.oid && c.contype !== "t")
              .map((c) => `  CONSTRAINT ${quote(c.conname)} ${c.definition}`),
          ].join(",\n") +
          "\n);",
      );
      if (table.relrowsecurity)
        sql.push(`ALTER TABLE ${table.name} ENABLE ROW LEVEL SECURITY;`);
      if (table.relforcerowsecurity)
        sql.push(`ALTER TABLE ${table.name} FORCE ROW LEVEL SECURITY;`);
      emitted.add(table.oid);
    }
    const indexes = (
      await db.query<{ definition: string }>(
        `SELECT pg_get_indexdef(i.indexrelid) definition FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid WHERE ${predicate} AND NOT EXISTS(SELECT 1 FROM pg_constraint k WHERE k.conindid=i.indexrelid) ORDER BY c.relname,i.indexrelid::regclass::text`,
      )
    ).rows;
    sql.push(...indexes.map((i) => i.definition + ";"));
    const functions = (
      await db.query<{
        oid: number;
        signature: string;
        definition: string;
        acl: boolean;
      }>(
        "SELECT oid,oid::regprocedure::text signature,pg_get_functiondef(oid) definition,proacl IS NOT NULL acl FROM pg_proc WHERE pronamespace='accounting'::regnamespace OR (pronamespace='public'::regnamespace AND proname LIKE 'business_profile%') ORDER BY proname,pg_get_function_identity_arguments(oid)",
      )
    ).rows;
    sql.push(...functions.map((f) => f.definition + ";"));
    async function grants(
      kind: string,
      name: string,
      catalog: string,
      oid: number,
      field: string,
    ) {
      sql.push(
        `REVOKE ALL ON ${kind} ${name} FROM PUBLIC, anon, authenticated, service_role;`,
      );
      const rows = (
        await db.query<{
          role: string;
          privilege_type: string;
          is_grantable: boolean;
        }>(
          `SELECT CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END role,a.privilege_type,a.is_grantable FROM ${catalog} c,aclexplode(c.${field}) a WHERE c.oid=$1`,
          [oid],
        )
      ).rows;
      for (const a of rows)
        sql.push(
          `GRANT ${a.privilege_type} ON ${kind} ${name} TO ${a.role === "PUBLIC" ? "PUBLIC" : quote(a.role)}${a.is_grantable ? " WITH GRANT OPTION" : ""};`,
        );
    }
    for (const t of tables)
      if (t.acl) await grants("TABLE", t.name, "pg_class", t.oid, "relacl");
    for (const f of functions)
      if (f.acl)
        await grants("FUNCTION", f.signature, "pg_proc", f.oid, "proacl");
    const sequences = (
      await db.query<{ oid: number; name: string }>(
        "SELECT oid,oid::regclass::text name FROM pg_class WHERE relnamespace='accounting'::regnamespace AND relkind='S' AND relacl IS NOT NULL",
      )
    ).rows;
    for (const s of sequences)
      await grants("SEQUENCE", s.name, "pg_class", s.oid, "relacl");
    const triggers = (
      await db.query<{ definition: string }>(
        `SELECT pg_get_triggerdef(t.oid) definition FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE ${predicate} AND NOT t.tgisinternal ORDER BY c.relname,t.tgname`,
      )
    ).rows;
    sql.push(...triggers.map((t) => t.definition + ";"));
    const policies = (
      await db.query<{
        schemaname: string;
        tablename: string;
        policyname: string;
        permissive: string;
        roles: string[];
        cmd: string;
        qual: string | null;
        with_check: string | null;
      }>(
        "SELECT * FROM pg_policies WHERE schemaname='accounting' OR tablename='business_profile' OR policyname LIKE 'accounting_%' ORDER BY schemaname,tablename,policyname",
      )
    ).rows;
    for (const p of policies)
      sql.push(
        `CREATE POLICY ${quote(p.policyname)} ON ${p.schemaname}.${p.tablename} AS ${p.permissive} FOR ${p.cmd} TO ${p.roles.map((r) => (r === "public" ? "PUBLIC" : quote(r))).join(", ")}${p.qual ? ` USING (${p.qual})` : ""}${p.with_check ? ` WITH CHECK (${p.with_check})` : ""};`,
      );
    // These rows are generic defaults from the fresh migrations, never transaction fixtures.
    const accounts = (
      await db.query<{
        name: string;
        type: string;
        subtype: string;
        system_purpose: string | null;
      }>(
        "SELECT name,type,subtype,system_purpose FROM accounting.accounts ORDER BY name",
      )
    ).rows;
    if (accounts.length !== 17)
      throw new Error("Unexpected seed chart; review before regenerating.");
    sql.push(
      "INSERT INTO public.business_profile(legal_name,entity_type,tax_classification) VALUES ('Valiance Media LLC','llc','s_corp');",
    );
    sql.push(
      "INSERT INTO accounting.accounts(name,type,subtype,system_purpose) VALUES\n" +
        accounts
          .map(
            (a) =>
              ` (${[a.name, a.type, a.subtype, a.system_purpose].map((v) => (v === null ? "NULL" : literal(v))).join(",")})`,
          )
          .join(",\n") +
        ";",
    );
    const bucket = (
      await db.query<{ definition: string }>(
        "SELECT format('INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES (%L,%L,%L,%L,%L);',id,name,public,file_size_limit,allowed_mime_types) definition FROM storage.buckets WHERE id='accounting-private'",
      )
    ).rows;
    sql.push(
      ...bucket.map((b) => b.definition),
      "SET check_function_bodies = true;",
      "-- ACCOUNTING CATALOG END",
    );
    const path = new URL("../supabase/schema/schema.sql", import.meta.url);
    const previous = await readFile(path, "utf8");
    const start = previous.indexOf("-- ACCOUNTING ");
    if (start < 0) throw new Error("Canonical accounting boundary is missing.");
    await writeFile(path, previous.slice(0, start) + sql.join("\n\n") + "\n");
    console.log(
      `Canonical catalog regenerated: ${tables.length} tables including business_profile, ${functions.length} functions, ${triggers.length} triggers, 17 generic chart accounts.`,
    );
  } finally {
    await db.close();
  }
}
main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
